### ISSUE TITLE
loadDbCmd bug

### ISSUE THREAD

**Issue by phillipcheng** [phillipcheng/log.analysis#150]
sql generated: tableName*, load multiple times when exits multiple input files belong to the same table.

table1-r-0001
table1-r-0002
table1-r-0003

**Comment by hanzac** [comment]
I don't think it could happen in MR mode.

The code of copy sql for hive:
String.format("load data inpath '%s%s' into table %s.%s", rootWebHdfs, csvFileName, dbschema, tn);

The code of copy sql for vertica:
        copysql.append(String.format(") SOURCE Hdfs(url='%s%s*',username='%s') delimiter ',';", rootWebHdfs, csvFileName, username));

Both pass the full file path in MR mode, so it's not possible to load one file multiple times.

**Comment by phillipcheng** [comment]
check csv compatible with schema, if not, normalize csv input

**Comment by hanzac** [comment]
Implemented CsvNormalizeCmd to normalize the csv file according to the schema
This is usually done before the LoadDataCmd to assure the csv file is compatible with the data base table

Use TextInputFormat or NLineInputFormat.

Cmd parameters inherit from the SchemaETLCmd, sample Cmd parameters:
schema.file=/etltest/csvnorm/schema
file.table.map=filename.substring(0,filename.indexOf('-r-'))
